# Generated by Django 2.1.3 on 2018-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_signup',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
