# Generated by Django 2.1.3 on 2018-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoapp', '0003_auto_20181204_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
